# Generated by Django 2.0.6 on 2018-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_docker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crash',
            name='id',
        ),
        migrations.RemoveField(
            model_name='docker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='id',
        ),
        migrations.AddField(
            model_name='vm',
            name='Os',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crash',
            name='Crash_Name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docker',
            name='Docker_Name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docker',
            name='Fuzzer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docker',
            name='Port',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vm',
            name='VM_Name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
