# Generated by Django 2.0.6 on 2018-06-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180608_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='Crash_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crash',
            name='Exploitable',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crash',
            name='Program',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vm',
            name='VM_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
